groups:
  - name: devs # name of the group
    reviewers: 1 # how many reviewers do you want to assign?
    usernames: # github usernames of the reviewers
      - stekman08

  - name: infra # you can have multiple groups, it will evaluate them separately
    reviewers: 1
    usernames:
      - peevees
